In [13]:
import cv2
import numpy as np
from PIL import Image

In [9]:
def get_boundaries(color):
    c=np.uint8([[color]])
    hsvC = cv2.cvtColor(c,cv2.COLOR_BGR2HSV)
    lower_limit = hsvC[0][0][0]-10,100,100
    upper_limit = hsvC[0][0][0]+10,255,255
    lower_limit = np.array(lower_limit,dtype=np.uint8)
    upper_limit = np.array(upper_limit,dtype=np.uint8)
    print(lower_limit,upper_limit)
    return lower_limit,upper_limit

In [10]:
yellow = [0,255,255]
cap = cv2.VideoCapture(0)

In [16]:
while True:
    ret,frame = cap.read()
    hsv_image  = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    lower_limit, upper_limit =get_boundaries(color=yellow)
    mask = cv2.inRange(hsv_image, lower_limit, upper_limit)
    mask1 = Image.fromarray(mask)
    box = mask1.getbbox()
    if box is not None:
        x1,y1,x2,y2 =box
        frame_b = cv2.rectangle(frame,(x1,y1),(y2,y2),(0.255,0),5)
    print(box)
    cv2.imshow('frame',frame_b)
    print(ret)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100

[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
(0, 0, 399, 125)
True
[ 20 100 100] [ 40 255 255]
(0, 0, 399, 125)
True
[ 20 100 100] [ 40 255 255]
(0, 20, 379, 123)
True
[ 20 100 100] [ 40 255 255]
(0, 20, 379, 123)
True
[ 20 100 100] [ 40 255 255]
(354, 89, 355, 91)
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 2

[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100] [ 40 255 255]
None
True
[ 20 100 100

KeyboardInterrupt: 